Feat/met 3128 record parsing and augmenting
europeana/metis-framework pull request #407
Opened 2020-12-21 11:57 UTC by jochen-vermeulen

2020-12-21 15:54 UTC, stzanakis requested changes
My comments mostly reflect code principles, more specifically for equals/hashcode where I think we should not transparently enforce implementations of it. But rather give freedom to the implementer. The fact that we use/implement them in a specific manner shouldn't need to be enforced to another implementation.
Any strong opinions on this?

2020-12-21 15:54 UTC, stzanakis commented on metis-enrichment/metis-enrichment-common/src/main/java/eu/europeana/enrichment/api/internal/AbstractReferenceTerm.java
> +    if (!(otherObject instanceof ReferenceTerm)) {
Why change this?
It's comparing here the interface type which it shouldn't and it's not symmetrical.
I think sonar will complain for this too

2020-12-21 15:54 UTC, stzanakis commented on metis-enrichment/metis-enrichment-common/src/main/java/eu/europeana/enrichment/api/internal/AbstractSearchTerm.java
> +    if (!(otherObject instanceof SearchTerm)) {
Same here

2020-12-21 15:54 UTC, stzanakis commented on metis-enrichment/metis-enrichment-common/src/main/java/eu/europeana/enrichment/api/internal/SearchTerm.java
> +  /**
Equals and hashCode shouldn't be in the interface imo.
The implementer should decide if the equals should be applied on the implementing class or not.
Btw they were removed on a previous review.

2020-12-21 15:54 UTC, stzanakis commented on metis-enrichment/metis-enrichment-common/src/main/java/eu/europeana/enrichment/api/internal/ReferenceTerm.java
> +
Same here 

"Equals and hashCode shouldn't be in the interface imo.
The implementer should decide if the equals should be applied on the implementing class or not.
Btw they were removed on a previous review."

2020-12-21 15:54 UTC, stzanakis commented on metis-enrichment/metis-enrichment-common/src/main/java/eu/europeana/enrichment/api/internal/ReferenceTermContext.java
> -  @Override
I think equals and hashcode should be declared here too, preferably with using the new fields or just by using super

2020-12-21 15:54 UTC, stzanakis commented on metis-enrichment/metis-enrichment-common/src/main/java/eu/europeana/enrichment/api/internal/SearchTermContext.java
> -  @Override
Same here 

"I think equals and hashcode should be declared here too, preferably with using the new fields or just by using super"

2020-12-21 15:54 UTC, stzanakis commented on metis-enrichment/metis-enrichment-common/src/main/java/eu/europeana/enrichment/api/internal/SearchTermImpl.java
> +  }
Same here

"I think equals and hashcode should be declared here too, preferably with using the new fields or just by using super"

2020-12-21 15:54 UTC, stzanakis commented on metis-enrichment/metis-enrichment-common/src/main/java/eu/europeana/enrichment/api/internal/ReferenceTermImpl.java
> +  }
Same here:

"I think equals and hashcode should be declared here too, preferably with using the new fields or just by using super"

2020-12-21 15:54 UTC, stzanakis commented on metis-enrichment/metis-enrichment-common/src/main/java/eu/europeana/enrichment/api/internal/AbstractReferenceTerm.java
> +  public final boolean equals(Object otherObject) {
Why final here, were are enforcing equals/hashcode in the hierarchy which I believe we should not

2020-12-21 15:54 UTC, stzanakis commented on metis-enrichment/metis-enrichment-common/src/main/java/eu/europeana/enrichment/api/internal/AbstractSearchTerm.java
> +  public final boolean equals(Object otherObject) {
Same here:

"Why final here, were are enforcing equals/hashcode in the hierarchy which I believe we should not"

2020-12-22 10:17 UTC, jochen-vermeulen commented
The implementation of equals and hashcode were made to comply with an old version of the EntityResolver interface (where it was important for the input objects to strictly satisfy equality conditions). But I changed the interface later to use generics, so that these strict conditions are no longer needed (but they were kept in place).

I now removed them, in this case that's fine. But perhaps in other situations there may be cases like this... anyway, that's not important now.

2020-12-22 12:12 UTC, merged