MET-3240 Fix transformation xslt parameters
europeana/metis-framework pull request #430
Opened 2021-03-04 10:19 UTC by stzanakis

2021-03-04 10:54 UTC, jochen-vermeulen requested changes
I have not completed my review. If this PR is to be merged, we'll have to look at it carefully again.

2021-03-04 10:54 UTC, jochen-vermeulen commented on metis-core/metis-core-service/src/main/java/eu/europeana/metis/core/service/WorkflowExecutionFactory.java
> +    pluginMetadata.setDatasetName(dataset.getDatasetName());
We are sure that in eCloud this parameter is ONLY used as input for our validation service, right?

2021-03-04 10:54 UTC, jochen-vermeulen commented on metis-data-checker/metis-data-checker-service/src/main/java/eu/europeana/metis/data/checker/service/executor/ValidationTask.java
>      final EuropeanaGeneratedIdsMap europeanaGeneratedIdsMap = new EuropeanaIdCreator()
This variable is no longer used.

2021-03-05 16:44 UTC, stzanakis commented
Not to be merged, xslt issues resolved on the xslt itself.
In the future changes on the xslt that require code changes should be reviewed beforehand.

2021-03-05 16:44 UTC, closed without merging