MET-4472 New Tier Calculation for 3D
europeana/metis-framework pull request #530
Opened 2022-05-11 12:38 UTC by JoanaCMS

2022-05-16 13:46 UTC, stzanakis requested changes

2022-05-17 09:23 UTC, JoanaCMS commented on metis-indexing/src/main/java/eu/europeana/indexing/tiers/media/ThreeDClassifier.java
> +    if(webResource == null){
Changed it

2022-05-17 09:44 UTC, JoanaCMS commented on metis-indexing/src/main/java/eu/europeana/indexing/tiers/media/ThreeDClassifier.java
> +    if(hasMediaResourceThatIsNotImageOrPdf(webResource) && hasLicenseType(webResource,LicenseType.OPEN)){
I see what you mean, I will remove the license evaluation part. It was mentioned in the document which tier to gives based on the type of license as well, AbstractMediaClassifier already handles it then?

2022-05-17 10:07 UTC, JoanaCMS commented on metis-indexing/src/main/java/eu/europeana/indexing/tiers/media/ThreeDClassifier.java
> +  private boolean hasMediaResourceThatIsNotImageOrPdf(WebResourceWrapper webResource){
Just separated them

2022-05-17 10:47 UTC, JoanaCMS commented on metis-indexing/src/main/java/eu/europeana/indexing/tiers/media/ThreeDClassifier.java
> +            !mimeType.contains("application/pdf");
Just saw the check in TextClassifier and re-used it here

2022-05-18 06:32 UTC, stzanakis commented on metis-indexing/src/main/java/eu/europeana/indexing/tiers/media/ThreeDClassifier.java
>    MediaTier classifyWebResource(WebResourceWrapper webResource, boolean hasLandingPage, boolean hasEmbeddableMedia) {
Looks good now!

2022-05-18 06:33 UTC, merged