Feat/MET-2018_MET-4364 error report mechanism dereference enrichment
europeana/metis-framework pull request #587
Opened 2022-10-27 08:10 UTC by jeortizquan

2022-12-06 16:23 UTC, stzanakis reviewed
Seems okay overall.
There are some improvements or considerations though that we could apply.
Please have a look.

2022-12-07 15:17 UTC, jeortizquan commented on metis-enrichment/metis-enrichment-client/src/main/java/eu/europeana/enrichment/rest/client/dereference/Dereferencer.java
> +  HashSet<ReportMessage> dereference(final RDF rdf);
Updated to `Set` interface.

2022-12-07 15:22 UTC, jeortizquan commented on metis-enrichment/metis-enrichment-client/src/main/java/eu/europeana/enrichment/rest/client/report/ProcessedResult.java
> +   * @param processedRecord
Updated documentation.

2022-12-07 15:27 UTC, jeortizquan commented on metis-enrichment/metis-enrichment-client/src/main/java/eu/europeana/enrichment/rest/client/report/ReportMessage.java
> +  private Mode mode;
done.

2022-12-07 16:35 UTC, jeortizquan commented on metis-enrichment/metis-enrichment-client/src/main/java/eu/europeana/enrichment/rest/client/dereference/DereferencerImpl.java
> +        .map(id -> {
extracted functions 1st phase.

2022-12-07 17:07 UTC, jeortizquan commented on metis-enrichment/metis-enrichment-client/src/main/resources/enrichment-sequence-diagram.txt
> +sequenceDiagram
removed.

2022-12-08 07:51 UTC, jeortizquan commented on metis-enrichment/metis-enrichment-client/pom.xml
> +      <version>2.34.0</version>
added.

2022-12-08 07:56 UTC, jeortizquan commented on metis-enrichment/metis-enrichment-common/src/main/java/eu/europeana/enrichment/api/external/model/EnrichmentResultBaseWrapper.java
> +  private DereferenceResultStatus enrichmentStatus;
:sweat_smile: I forgot to rename it. done.

2022-12-12 13:21 UTC, jeortizquan commented on metis-enrichment/metis-enrichment-client/src/main/java/eu/europeana/enrichment/rest/client/report/ReportMessage.java
> +  public static final class ReportMessageBuilder {
Did some updates to the class taking your suggestions, see if they are better now.

2022-12-13 19:33 UTC, jeortizquan commented on metis-dereference/metis-dereference-service/src/main/java/eu/europeana/metis/dereference/service/MongoDereferenceService.java
> +      final Triple<EnrichmentBase, Vocabulary, DereferenceResultStatus> resource = computeEnrichmentBaseVocabularyTriple(resourceId);
Created result object to handle this.

2022-12-13 19:34 UTC, jeortizquan commented on metis-enrichment/metis-enrichment-client/src/main/java/eu/europeana/enrichment/rest/client/dereference/DereferencerImpl.java
> +  public Pair<List<EnrichmentBase>, HashSet<ReportMessage>> dereferenceEntities(Set<String> resourceIds) {
Created an object to handle the pair and triple.

2022-12-13 22:43 UTC, jeortizquan commented on metis-enrichment/metis-enrichment-client/src/test/resources/enriched.xml
> +<?xml version="1.0" encoding="UTF-8"?>
removed.

2022-12-19 17:46 UTC, jeortizquan commented on metis-enrichment/metis-enrichment-client/src/test/java/eu/europeana/enrichment/rest/client/EnrichmentWorkerImplTest.java
> +    enricherProvider.setEnrichmentPropertiesValues("https://entity-management-production.eanadev.org/entity",
Added the mocks.

2022-12-19 18:44 UTC, jeortizquan commented on metis-enrichment/metis-enrichment-rest/src/main/java/eu/europeana/enrichment/rest/EnrichmentController.java
> +        .map(item -> new EnrichmentResultBaseWrapper(item, DereferenceResultStatus.SUCCESS)).collect(Collectors.toList());
done.

2022-12-20 15:17 UTC, stzanakis requested changes

2022-12-20 15:17 UTC, stzanakis commented on metis-enrichment/metis-enrichment-service/src/main/java/eu/europeana/enrichment/service/EnrichmentService.java
> +import eu.europeana.enrichment.api.external.DereferenceResultStatus;
Not used

2022-12-21 12:30 UTC, jeortizquan commented on metis-dereference/metis-dereference-common/pom.xml
> +      <scope>compile</scope>
grouped and moved at the start where all of them they are.

2022-12-21 12:30 UTC, jeortizquan commented on metis-enrichment/metis-enrichment-common/src/main/java/eu/europeana/enrichment/api/external/model/EnrichmentResultBaseWrapper.java
> +  public void setDereferenceStatus(DereferenceResultStatus dereferenceStatus) {
removed unused code.

2022-12-21 12:47 UTC, jeortizquan commented on metis-dereference/metis-dereference-service/src/main/java/eu/europeana/metis/dereference/service/MongoDereferenceService.java
> +   * @return A collection of Pair dereferenced resources and the status of dereference process. Is not null, but could be empty.
documentation improved.

2022-12-21 12:49 UTC, jeortizquan commented on metis-dereference/metis-dereference-service/src/main/java/eu/europeana/metis/dereference/service/MongoDereferenceService.java
> +    final EnrichmentEntityVocabulary entityVocabularyTriple = computeEntityVocabularyTriple(resourceId,
It becomes simpler :smile:

2022-12-21 12:54 UTC, jeortizquan commented on metis-dereference/metis-dereference-service/src/main/java/eu/europeana/metis/dereference/service/MongoDereferenceService.java
> +      dereferenceResult = checkEmptyEnrichmentBaseAndVocabulary(dereferenceResult, resource);
Yes. thanks for noticing, It is an error of refactoring the code, I just removed the extra parameter and placed the variable where I needed.

2022-12-21 13:06 UTC, jeortizquan commented on metis-dereference/metis-dereference-service/src/main/java/eu/europeana/metis/dereference/service/MongoDereferenceService.java
>     * @throws TransformerException if an exception occurred during transformation of the original entity
Thanks, actually was not being catched the proper way, updated this section.

2022-12-21 13:38 UTC, jeortizquan commented on metis-dereference/metis-dereference-service/src/main/java/eu/europeana/metis/dereference/service/MongoDereferenceService.java
> +      dereferenceResult = new DereferenceResult(Collections.emptyList(), DereferenceResultStatus.ENTITY_FOUND_XML_XLT_ERROR);
refactored. done.

2022-12-21 13:39 UTC, jeortizquan commented on metis-dereference/metis-dereference-service/src/main/java/eu/europeana/metis/dereference/service/MongoDereferenceService.java
> +      //Triple<EnrichmentBase, Vocabulary, DereferenceResultStatus>
removed. done.

2022-12-21 13:43 UTC, jeortizquan commented on metis-enrichment/metis-enrichment-client/src/main/java/eu/europeana/enrichment/rest/client/enrichment/EnricherImpl.java
> +  private static Throwable findRootCause(Throwable throwable) {
Refactored to use apache.

2022-12-21 13:46 UTC, jeortizquan commented on metis-enrichment/metis-enrichment-client/src/main/java/eu/europeana/enrichment/rest/client/enrichment/EnricherImpl.java
> +    List<HttpStatus> warningStatuses = Arrays.stream(HttpStatus.values())
Excellent. Moved to a static field.

2022-12-21 13:54 UTC, jeortizquan commented on metis-dereference/metis-dereference-service/src/main/java/eu/europeana/metis/dereference/service/EnrichmentEntityVocabulary.java
> +public class EnrichmentEntityVocabulary {
done.

2022-12-21 14:57 UTC, jeortizquan commented on metis-enrichment/metis-enrichment-client/src/main/java/eu/europeana/enrichment/rest/client/report/ReportMessage.java
> +public final class ReportMessage {
Renamed to report

2022-12-21 15:42 UTC, jeortizquan commented on metis-dereference/metis-dereference-service/src/main/java/eu/europeana/metis/dereference/service/MongoDereferenceService.java
> +      return new EnrichmentEntityVocabulary(enrichmentBaseVocabulary.getEnrichmentBase(),
The code was entangled with processing similar conditions, I just refactored it and it became simpler, reusing a constructor.

2022-12-21 15:44 UTC, jeortizquan commented on metis-enrichment/metis-enrichment-client/src/main/java/eu/europeana/enrichment/rest/client/report/ReportMessage.java
> +  public ReportMessage build() {
I simplified it to a single class due sonar reported as duplicated code.

2022-12-21 15:47 UTC, jeortizquan commented on metis-enrichment/metis-enrichment-client/src/main/java/eu/europeana/enrichment/rest/client/EnrichmentWorkerImpl.java
> +      e = new IllegalArgumentException("Input RDF cannot be null.");
Simplified it.

2022-12-21 15:55 UTC, jeortizquan commented on metis-enrichment/metis-enrichment-rest/src/main/java/eu/europeana/enrichment/rest/EnrichmentController.java
> +        .map(item -> new EnrichmentResultBaseWrapper(item.getEnrichmentBaseList(), DereferenceResultStatus.SUCCESS))
I am defining it to `null`. in this class just for compatibility.

2022-12-22 09:36 UTC, merged