MET-5757 Integrated new Media Processor
europeana/metis-framework pull request #654
Opened 2024-02-12 14:59 UTC by JoanaCMS

2024-02-15 14:55 UTC, jeortizquan requested changes

2024-02-15 14:55 UTC, jeortizquan commented on metis-media-service/src/test/java/eu/europeana/metis/mediaprocessing/extraction/MediaExtractorImplTest.java
update unit test for `MediaType.THREE_D`
```
@Test
  void testChooseMediaProcessor() {
    assertSame(imageProcessor, mediaExtractor.chooseMediaProcessor(MediaType.IMAGE));
    assertSame(audioVideoProcessor, mediaExtractor.chooseMediaProcessor(MediaType.AUDIO));
    assertSame(audioVideoProcessor, mediaExtractor.chooseMediaProcessor(MediaType.VIDEO));
    assertSame(textProcessor, mediaExtractor.chooseMediaProcessor(MediaType.TEXT));
    assertNull(mediaExtractor.chooseMediaProcessor(MediaType.OTHER));
  }
```

2024-02-15 14:55 UTC, jeortizquan commented on metis-media-service/src/test/java/eu/europeana/metis/mediaprocessing/extraction/MediaExtractorImplTest.java
update unit test for `MediaType.THREE_D` to cover Media3d should not download the full file.
```
  @Test
  void testShouldDownloadForFullProcessing() {
    doReturn(true).when(imageProcessor).downloadResourceForFullProcessing();
    doReturn(true).when(textProcessor).downloadResourceForFullProcessing();
    doReturn(false).when(audioVideoProcessor).downloadResourceForFullProcessing();
    assertTrue(mediaExtractor.shouldDownloadForFullProcessing("image/unknown_type"));
    assertTrue(mediaExtractor.shouldDownloadForFullProcessing("text/unknown_type"));
    assertFalse(mediaExtractor.shouldDownloadForFullProcessing("audio/unknown_type"));
    assertFalse(mediaExtractor.shouldDownloadForFullProcessing("video/unknown_type"));
    assertFalse(mediaExtractor.shouldDownloadForFullProcessing("unknown_type"));
  }
```

2024-02-15 14:55 UTC, jeortizquan commented on metis-media-service/src/main/java/eu/europeana/metis/mediaprocessing/model/Media3dResourceMetadata.java
remove unused imports

2024-02-15 14:59 UTC, JoanaCMS commented on metis-media-service/src/main/java/eu/europeana/metis/mediaprocessing/model/Media3dResourceMetadata.java
Removed

2024-02-15 15:02 UTC, JoanaCMS commented on metis-media-service/src/test/java/eu/europeana/metis/mediaprocessing/extraction/MediaExtractorImplTest.java
Added

2024-02-16 09:24 UTC, jeortizquan approved these changes

2024-02-16 09:26 UTC, merged