MET-5692 Fixing dereference status inconsistency
europeana/metis-framework pull request #670
Opened 2024-04-22 13:34 UTC by JoanaCMS

…formation result

2024-04-29 10:57 UTC, jeortizquan reviewed
I just had a look and I have a suggestion to add a simple unit test that cover the case of multiple calls to the same endpoint of dereference.

The change follows for `MongoDereferenceServiceTest.java`
update the `prepare` method to simulate the behaviour of what was happening on the bug with the cache.
```
 @BeforeEach
  void prepare() {
    embeddedLocalhostMongo.start();
    String mongoHost = embeddedLocalhostMongo.getMongoHost();
    int mongoPort = embeddedLocalhostMongo.getMongoPort();

    MongoClient mongoClient = MongoClients.create(String.format("mongodb://%s:%s", mongoHost, mongoPort));
    VocabularyDao vocabularyDao = new VocabularyDao(mongoClient, "voctest") {
      {
        vocabularyDaoDatastore = this.getDatastore();
      }
    };
    ProcessedEntityDao processedEntityDao = new ProcessedEntityDao(mongoClient, "processedentity");
    service = spy(new MongoDereferenceService(new RdfRetriever(), processedEntityDao, vocabularyDao));
  }
```

suggested unit test to include
```
  @Test
  void testDereference_IdempotentResult() {
    final String entityId = "https://d-nb.info/gnd/XXXX";

    //Test the method
    DereferenceResult result = service.dereference(entityId);
    assertNotNull(result);
    assertTrue(result.getEnrichmentBasesAsList().isEmpty());
    assertEquals(DereferenceResultStatus.NO_VOCABULARY_MATCHING, result.getDereferenceStatus());
    //Test it again it should remain consistent
    result = service.dereference(entityId);
    assertNotNull(result);
    assertTrue(result.getEnrichmentBasesAsList().isEmpty());
    assertEquals(DereferenceResultStatus.NO_VOCABULARY_MATCHING, result.getDereferenceStatus());
  }
```

2024-05-06 07:04 UTC, jeortizquan requested changes
Hi, I have suggested two options to simulate the caching behaviour. the options are mutually exclusive. is either to implement option a) or option b). I noticed the actual mock is not simulating the cache behaviour: first query to `null` and second query to return the `entity`.

2024-05-06 07:55 UTC, JoanaCMS commented on metis-dereference/metis-dereference-service/src/test/java/eu/europeana/metis/dereference/service/MongoDereferenceServiceTest.java
> +    ProcessedEntityDao processedEntityDao = mock(ProcessedEntityDao.class, "processedEntity");
I went with this option and the build seems to be going fine

2024-05-06 10:10 UTC, jeortizquan approved these changes

2024-05-06 10:10 UTC, merged